spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: fujia
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oj-backend-user-service
          uri: lb://oj-backend-user-service #lb负载均衡，根据服务名找到对应的服务
          predicates:
            - Path=/api/user/**
        - id: oj-backend-question-service
          uri: lb://oj-backend-question-service #lb负载均衡，根据服务名找到对应的服务
          predicates:
            - Path=/api/question/**
        - id: oj-backend-judge-service
          uri: lb://oj-backend-judge-service #lb负载均衡，根据服务名找到对应的服务
          predicates:
            - Path=/api/judge/**
  application:
    name: oj-backend-gateway # 网关需要取nacos上找服务
  main:
    web-application-type: reactive
server:
  port: 8101
# 访问：http://localhost:8101/doc.html#/home
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
# 这个配置是不用看token是否合法 直接通过
gateway:
  excludedUrls: /api/user/get/login,/api/user/logout,/user/register,/api/user/update/my,/api/user/login,/user/getLoginUser,/api/user/register,/api/question/list/page/vo

